version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: laravel/framework
    versions:
    - 8.30.1
    - 8.31.0
    - 8.32.1
    - 8.35.0
    - 8.39.0
