version: '3'
services:
    app:
        build: .
        depends_on:
          - mysql
          - dynamodb-local
        volumes:
          - .:/var/www/html
        ports:
          - "8000:8000"
    mysql:
        image: mysql:5.7
        environment:
          MYSQL_DATABASE: lemonade-docker
          MYSQL_USER: user
          MYSQL_PASSWORD: lemonade-user
          MYSQL_ROOT_PASSWORD: lemonade-root
        volumes:
          - mysql-data:/var/lib/mysql
    dynamodb-local:
        command: "-jar DynamoDBLocal.jar -sharedDb -port 8001 -dbPath ./data"
        image: "amazon/dynamodb-local:latest"
        container_name: dynamodb-local
        ports:
          - "8001:8001"
        volumes:
          - "./docker/dynamodb:/home/dynamodblocal/data"
        working_dir: /home/dynamodblocal
        user: root
volumes:
  mysql-data:
    driver: local
